trying new buildback base

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -38,105 +38,149 @@ urlfor() {
 mkdir -p "$1" "$2"
 build=$(cd "$1/" && pwd)
 cache=$(cd "$2/" && pwd)
-buildpack=$(dirname $(dirname $0))
+buildpack=$(cd "$(dirname $0)/.." && pwd)
 arch=$(uname -m|tr A-Z a-z)
 if test $arch = x86_64
 then arch=amd64
 fi
 plat=$(uname|tr A-Z a-z)-$arch
 
-#echo "-----> remove gohperjs items, they are not used on heroku"
-#rm -rf $build/pages
-#find $build/static -name \*.js.map -exec rm {} \;
-
 # Python
 venv=$cache/venv
 mkdir -p $cache/pip
 python=python2.7
 PATH=$buildpack/$plat/bin:$venv/bin:$PATH
+steptxt="----->"
 
 virtualenv() {
     python "$buildpack/vendor/virtualenv-1.11.6/virtualenv.py" "$@"
 }
 
+warn() {
+    echo >&2 " !     $@"
+}
+
+step() {
+    echo "$steptxt $@"
+}
+
+start() {
+    echo -n "$steptxt $@... "
+}
+
+finished() {
+    echo "done"
+}
+
 if test -f $build/Godeps
 then
+    warn "Deprecated, old ./Godeps file found!"
+    warn "Please upgrade godeps (go get -u github.com/tools/godep) and"
+    warn "re-save your dependencies: godep save -r ./..."
     name=$(<$build/Godeps jq -r .ImportPath)
     ver=$(<$build/Godeps jq -r .GoVersion)
-elif test -d $build/Godeps
+elif test -f $build/Godeps/Godeps.json
 then
+    step "Checking Godeps/Godeps.json file."
+    if ! jq -r . < $build/Godeps/Godeps.json > /dev/null
+    then
+        warn "Bad Godeps/Godeps.json file"
+        exit 1
+    fi
     name=$(<$build/Godeps/Godeps.json jq -r .ImportPath)
     ver=$(<$build/Godeps/Godeps.json jq -r .GoVersion)
 elif test -f $build/.godir
 then
+    warn "Deprecated, .godir file found!"
+    warn "Please switch to godeps (github.com/tools/godep) ASAP"
     name=$(cat $build/.godir)
-    ver=go${GOVERSION:-1.3}
+    ver=go${GOVERSION:-1.4.2}
 else
-    echo >&2 " !     A .godir is required. For instructions:"
-    echo >&2 " !     http://mmcgrana.github.io/2012/09/getting-started-with-go-on-heroku"
+    warn "Godeps are required. For instructions:"
+    warn "https://devcenter.heroku.com/articles/go-support"
     exit 1
 fi
 
 file=${GOFILE:-$ver.$(uname|tr A-Z a-z)-amd64$(platext $ver).tar.gz}
 url=${GOURL:-$(urlfor $ver $file)}
-
 if test -e $build/bin && ! test -d $build/bin
 then
-    echo >&2 " !     File bin exists and is not a directory."
+    warn "File bin exists and is not a directory."
     exit 1
 fi
 
 if test -d $cache/$ver/go
 then
-    echo "-----> Using $ver"
+    step "Using $ver"
 else
     rm -rf $cache/* # be sure not to build up cruft
     mkdir -p $cache/$ver
     cd $cache/$ver
-    echo -n "-----> Installing $ver..."
-    curl -sO $url
-    tar zxf $file
-    rm -f $file
-    echo " done"
+    start "Installing $ver"
+        curl -sO $url
+        tar zxf $file
+        rm -f $file
+    finished
+    cd - >/dev/null
 fi
+
 
 mkdir -p $build/bin
 GOBIN=$build/bin export GOBIN
 GOROOT=$cache/$ver/go export GOROOT
-GOPATH=$build/.heroku/g export GOPATH
+GOPATH=$build/.heroku/go export GOPATH
 PATH=$GOROOT/bin:$PATH
 
-if  !(test -d $build/Godeps || (which hg >/dev/null && which bzr >/dev/null))
+step "Installing gopherjs support libs"
+go get github.com/gopherjs/jquery
+
+step "Working around problem with gopkg.in and fsnotify"
+go get github.com/go-fsnotify/fsnotify
+mkdir -p "$GOPATH/src/gopkg.in/"
+ln -s $GOPATH/src/github.com/go-fsnotify/fsnotify $GOPATH/src/gopkg.in/fsnotify.v1
+
+start "Installing gopherjs compiler"
+    go get github.com/gopherjs/gopherjs
+finished
+
+GOPHERJSOPTS="-m"
+GOPHERJS="$GOBIN/gopherjs $GOPHERJSOPTS"
+PAGEGEN=$GOBIN/pagegen
+
+if ! (test -d $build/Godeps || (which hg >/dev/null && which bzr >/dev/null))
 then
     echo
     echo "       Tired of waiting for bzr and hg?"
-    echo "       Try github.com/kr/godep for faster deploys."
+    echo "       Use github.com/tools/godep for faster deploys."
     echo
 
-    echo -n "       Installing Virtualenv..."
-    virtualenv --python $python --distribute --never-download --prompt='(venv) ' $venv > /dev/null 2>&1
-    . $venv/bin/activate > /dev/null 2>&1
-    echo " done"
+    start "Installing Virtualenv"
+        virtualenv --python $python --distribute --never-download --prompt='(venv) ' $venv > /dev/null 2>&1
+        . $venv/bin/activate > /dev/null 2>&1
+    finished
 
-    echo -n "       Installing Mercurial..."
-    pip install mercurial > /dev/null 2>&1
-    echo " done"
+    start "Installing Mercurial"
+        pip install mercurial > /dev/null 2>&1
+    finished
 
-    echo -n "       Installing Bazaar..."
-    pip install bzr > /dev/null 2>&1
-    echo " done"
+    start "Installing Bazaar"
+        pip install bzr > /dev/null 2>&1
+    finished
 fi
 
 p=$GOPATH/src/$name
 mkdir -p $p
 cp -R $build/* $p
 
+# Default to $SOURCE_VERSION environment variable
+GO_LINKER_VALUE=${SOURCE_VERSION}
+
 # allow apps to specify cgo flags and set up /app symlink so things like CGO_CFLAGS=-I/app/... work
 env_dir="$3"
 if [ -d "$env_dir" ]
 then
     ln -sfn $build /app/code
-    for key in CGO_CFLAGS CGO_CPPFLAGS CGO_CXXFLAGS CGO_LDFLAGS GO_GIT_DESCRIBE_SYMBOL
+  for key in CGO_CFLAGS CGO_CPPFLAGS CGO_CXXFLAGS CGO_LDFLAGS GO_LINKER_SYMBOL GO_LINKER_VALUE
     do
         if [ -f "$env_dir/$key" ]
         then
@@ -145,21 +189,29 @@ then
     done
 fi
 
+# If $GO_LINKER_SYMBOL and GO_LINKER_VALUE are set, tell the linker to DTRT
 FLAGS=(-tags heroku)
-if test -f "$env_dir/GO_GIT_DESCRIBE_SYMBOL"
+if [ -n "$GO_LINKER_SYMBOL" -a -n "$GO_LINKER_VALUE" ]
 then
-    git_describe=$(git describe --tags --always)
-    FLAGS=(${FLAGS[@]} -ldflags "-X $GO_GIT_DESCRIBE_SYMBOL $git_describe")
+  FLAGS=(${FLAGS[@]} -ldflags "-X $GO_LINKER_SYMBOL $GO_LINKER_VALUE")
 fi
 
 unset GIT_DIR # unset git dir or it will mess with goinstall
 cd $p
 if test -e $build/Godeps
 then
-    echo "-----> Running: godep go install ${FLAGS[@]} ./..."
+    step "Running: godep go install ${FLAGS[@]} ./..."
     godep go install "${FLAGS[@]}" ./...
+    export GOPATH=`godep path`:$GOPATH
+    if test -e $build/pages/Makefile; then
+        start "Compiling client side code in pages"
+        pushd pages
+        GOPHERJS="../$GOPHERJS" PAGEGEN="$PAGEGEN" make
+        popd
+        finished
+    fi
 else
-    echo "-----> Running: go get ${FLAGS[@]} ./..."
+    step "Running: go get ${FLAGS[@]} ./..."
     go get "${FLAGS[@]}" ./...
 fi
 
@@ -167,4 +219,4 @@ rm -rf $build/.heroku
 
 mkdir -p $build/.profile.d
 echo 'PATH=$PATH:$HOME/bin' > $build/.profile.d/go.sh
-
+cp $buildpack/vendor/concurrency.sh $build/.profile.d/
